services:
  frontend:
    build:
      context: ./web  # Carpeta del frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - proxy
    networks:
      - app_network

  microservicio_book:
    build:
      context: ./microservicioBook  # Carpeta del microservicioBook
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./microservicioBook/db:/data/db
    networks:
      - app_network

  proxy:
    build:
      context: ./proxy  # Carpeta del gateway o proxy
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - microservicio_book
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
